# Autogenerated wrapper script for Bun_jll for x86_64-w64-mingw32
export bun

JLLWrappers.@generate_wrapper_header("Bun")
JLLWrappers.@declare_executable_product(bun)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        bun,
        "bin\\bun.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
